export const BADGES = [
  {
    id: "first-spark",
    category: "lifetime",
    threshold: 1,
    title: "First Spark",
    icon: "spark",
    description: "You welcomed the very first star into your sky.",
  },
  {
    id: "tiny-angel",
    category: "lifetime",
    threshold: 3,
    title: "Tiny Angel",
    icon: "halo",
    description: "Three stars and the shrine already looks cherished.",
  },
  {
    id: "sweet-seven",
    category: "lifetime",
    threshold: 7,
    title: "Sweet Seven",
    icon: "ribbon",
    description: "Seven stars make the collection feel real and precious.",
  },
  {
    id: "two-week-darling",
    category: "lifetime",
    threshold: 14,
    title: "Two-Week Darling",
    icon: "heart",
    description: "Fourteen stars and your diary starts to feel luxurious.",
  },
  {
    id: "satin-crown",
    category: "lifetime",
    threshold: 21,
    title: "Satin Crown",
    icon: "crown",
    description: "Twenty-one stars unlock crown-tier pretty.",
  },
  {
    id: "thirty-star-princess",
    category: "lifetime",
    threshold: 30,
    title: "Thirty-Star Princess",
    icon: "medallion",
    description: "Thirty stars and the whole room levels up with you.",
  },
  {
    id: "golden-crown",
    category: "lifetime",
    threshold: 50,
    title: "Golden Crown",
    icon: "crown",
    description: "Fifty stars earns a truly ceremonial badge.",
  },
  {
    id: "stardust-century",
    category: "lifetime",
    threshold: 100,
    title: "Stardust Century",
    icon: "comet",
    description: "One hundred stars makes the shrine feel legendary.",
  },
  {
    id: "ribbon-run",
    category: "streak",
    threshold: 3,
    title: "Ribbon Run",
    icon: "ribbon",
    description: "Three consecutive days tied together with a neat satin bow.",
  },
  {
    id: "velvet-run",
    category: "streak",
    threshold: 5,
    title: "Velvet Run",
    icon: "heart",
    description: "Five days in a row makes the sky feel velvety smooth.",
  },
  {
    id: "silk-ribbon-run",
    category: "streak",
    threshold: 7,
    title: "Silk Ribbon Run",
    icon: "moon",
    description: "Seven days of steady shine looks properly polished.",
  },
  {
    id: "moon-chain",
    category: "streak",
    threshold: 10,
    title: "Moon Chain",
    icon: "moon",
    description: "Ten linked days build a proper constellation chain.",
  },
  {
    id: "bloom-week",
    category: "weekly",
    threshold: 3,
    title: "Bloom Week",
    icon: "petal",
    description: "Three stars in any seven-day window keeps the garden alive.",
  },
  {
    id: "shining-week",
    category: "weekly",
    threshold: 5,
    title: "Shining Week",
    icon: "star",
    description: "Five stars in seven days deserves a brighter ribbon crown.",
  },
  {
    id: "petal-basket",
    category: "monthly",
    threshold: 10,
    title: "Petal Basket",
    icon: "petal",
    description: "Ten stars in a month turns effort into a whole bouquet.",
  },
  {
    id: "full-bloom",
    category: "monthly",
    threshold: 15,
    title: "Full Bloom",
    icon: "flower",
    description: "Fifteen monthly stars and the whole shrine opens wider.",
  },
  {
    id: "palace-garden",
    category: "monthly",
    threshold: 20,
    title: "Palace Garden",
    icon: "garden",
    description: "Twenty monthly stars fills the room with lush praise.",
  },
  {
    id: "comeback-charm",
    category: "comeback",
    title: "Comeback Charm",
    icon: "spark",
    description: "You returned after a quiet gap and the sky welcomed you softly.",
  },
  {
    id: "monday-bow",
    category: "weekday",
    weekday: 1,
    title: "Monday Bow",
    icon: "bow",
    description: "A star earned on a Monday deserves a ribbon of its own.",
  },
  {
    id: "weekend-sparkle",
    category: "weekend",
    title: "Weekend Sparkle",
    icon: "spark",
    description: "Your weekend glitter still counts and still looks lovely.",
  },
  {
    id: "ribbon-beginning",
    category: "first_of_month",
    title: "Ribbon Beginning",
    icon: "ribbon",
    description: "You opened a month with a first-of-month star.",
  },
  {
    id: "rare-comet",
    category: "rare",
    title: "Rare Comet",
    icon: "comet",
    description: "A deterministic rare sparkle day crossed your sky.",
  },
];
